---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-secret
  namespace: deuseda
spec:
  encryptedData:
    postgres-password: AgCGYl/BpPmhap/mx7GbzI222iToz0FgczYCKax6mODDOIITJ8i2xw+ydmApKESzdUSD40JwfMuMSelgZhi4nt24nitr4lxA5kQVeF598yJtWARLt8FleGxdWWCMhFO84S8fTTTmYxo8crRQk1gAeok40lkM3AzwF5guYHfWBtA1sqW2GxEoQbCKvmCG9edzl9Lw45XhdN8RfLBR6zbrFIKAf5u9FMGIvEVvCcDHEAZ9Leh76BGCsDnJc3a+oSLdZG0Hw7IuMAZDRI4jjl4kRXzk+1qwLiEPJCjrGr/fCzD2fVVxxanHN2IHk/t29BPSTsWnfInSmiLAgco+Nh3ZYSwT7pSQbG+uWDE/Bb5c3oF82EDJi4ykU1HRpkI5sQkREkaK5cJ75EprttkvJPVqNTaDbQpJmlP6qwglzeK0ulypel99pN+Jf3GxY+xFJC0gQyJVfqUBl4tXC8AKregLDwoMfZy1R7Ecpq58d54ySO6K2f098TdnmNroqgyi7V/bU6Zoek4LwR24KYlZhtx3Sl3qpT1j1bV57qS/TPMqoQSZzY97wCDR4MAiXvw8CNyuqOEjxtrfUKepvdFa7c7tYdPWSq5Mz0THIbsifQ91UNKH8U4h1ToqV72wa9cLM7eN9aSZ/KM05UEdlKH/A/p3winnwj+OeYdUxxk78bIopDy0u/weN3Oen0jPYWY5TtNEHrjKOKH2LEPpS6QjLTOiuSvO9Z7Ap5cqxjvIaSSAOxOGN4bqII2keX2hJcpQcepF+unYuaRP0XtqLokslJMeo9qn
  template:
    metadata:
      name: postgres-secret
      namespace: deuseda
    type: Opaque
