version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: deuseda-backend
    environment:
      RUST_LOG: info
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 8080
      JWT_SECRET: ${JWT_SECRET:-your-secret-key-change-in-production}
      SSH_HOST: ${SSH_HOST:-host.docker.internal}
      SSH_PORT: ${SSH_PORT:-22}
    ports:
      - "8080:8080"
    networks:
      - deuseda-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: deuseda-frontend
    ports:
      - "80:80"
    networks:
      - deuseda-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  deuseda-network:
    driver: bridge
