---
apiVersion: v1
kind: Service
metadata:
  name: deuseda-backend
  namespace: default
spec:
  selector:
    app: deuseda-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deuseda-backend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deuseda-backend
  template:
    metadata:
      labels:
        app: deuseda-backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/YOUR_GITHUB_USERNAME/deuseda-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  name: deuseda-config
                  key: SERVER_HOST
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: deuseda-config
                  key: SERVER_PORT
            - name: RUST_LOG
              valueFrom:
                configMapKeyRef:
                  name: deuseda-config
                  key: RUST_LOG
            - name: SSH_HOST
              valueFrom:
                configMapKeyRef:
                  name: deuseda-config
                  key: SSH_HOST
            - name: SSH_PORT
              valueFrom:
                configMapKeyRef:
                  name: deuseda-config
                  key: SSH_PORT
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: deuseda-secret
                  key: DATABASE_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: deuseda-secret
                  key: JWT_SECRET
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
