apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: deuseda-ingress
  namespace: default
  annotations:
    konghq.com/strip-path: "false"
    konghq.com/protocols: "https"
    konghq.com/https-redirect-status-code: "301"
spec:
  ingressClassName: kong
  rules:
    - host: console.deuseda.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: deuseda-backend
                port:
                  number: 8080
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: deuseda-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: deuseda-frontend
                port:
                  number: 80
  tls:
    - hosts:
        - console.deuseda.com
      secretName: deuseda-tls-cert
