apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: deuseda

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/name: deuseda
  app.kubernetes.io/managed-by: kustomize
