# ⚠️  WARNING: This file contains EXAMPLE secrets for development only.
# These secrets MUST be replaced in production!
#
# SECURITY RECOMMENDATIONS:
# 1. Use Sealed Secrets (bitnami-labs/sealed-secrets) for GitOps
# 2. Use External Secrets Operator for cloud secret managers (AWS/GCP/Azure)
# 3. Use kubectl create secret directly for manual management
# 4. NEVER commit real production secrets to Git
#
# To generate secure secrets:
#   openssl rand -base64 32

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  database: "deuseda_console"
  username: "deuseda"
  # ⚠️  CHANGE IN PRODUCTION - Generate with: openssl rand -base64 32
  password: "LOCAL_DEV_PASSWORD_CHANGE_ME"
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  # ⚠️  CHANGE IN PRODUCTION - Format: postgresql://user:password@host:port/database
  database-url: "postgresql://deuseda:LOCAL_DEV_PASSWORD_CHANGE_ME@deuseda-postgres:5432/deuseda_console"

  # ⚠️  CHANGE IN PRODUCTION - Generate with: openssl rand -base64 64
  jwt-secret: "LOCAL_DEV_JWT_SECRET_MUST_BE_CHANGED_IN_PRODUCTION_USE_STRONG_RANDOM_STRING"

  # SSH connection credentials (if needed)
  # ssh-private-key: ""
  # ssh-passphrase: ""
