apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namePrefix: dev-

labels:
  - pairs:
      environment: dev

replicas:
  - name: deuseda-backend
    count: 1
  - name: deuseda-frontend
    count: 1

images:
  - name: ghcr.io/YOUR_GITHUB_USERNAME/deuseda-backend
    newName: ghcr.io/YOUR_GITHUB_USERNAME/deuseda-backend
    newTag: develop
  - name: ghcr.io/YOUR_GITHUB_USERNAME/deuseda-frontend
    newName: ghcr.io/YOUR_GITHUB_USERNAME/deuseda-frontend
    newTag: develop

patchesStrategicMerge:
  - ingress-patch.yaml
